import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/modules/core/components/layouts/header/navbar'
import Provider from './providers'
import { IbmPlexSans } from '@/fonts/fonts'

const inter = Inter({ subsets: ['latin'] })
const ibmPlexSans = IbmPlexSans
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} ${ibmPlexSans.variable}`}>
				<Provider>
					<Navbar />
					{children}
				</Provider>
			</body>
		</html>
	)
}
